# Generated by Django 5.2.1 on 2025-05-29 11:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название филиала')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес филиала')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
            },
        ),
        migrations.CreateModel(
            name='GlossaryTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='Термин')),
                ('definition', models.TextField(verbose_name='Определение')),
                ('category', models.CharField(choices=[('general', 'Общие термины'), ('insurance', 'Страхование'), ('contract', 'Договор'), ('payment', 'Оплата'), ('faq', 'Часто задаваемые вопросы')], max_length=50, verbose_name='Категория')),
                ('is_faq', models.BooleanField(default=False, verbose_name='Это FAQ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Термин',
                'verbose_name_plural': 'Словарь терминов',
                'ordering': ['category', 'term'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(default='', max_length=100, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('experience_years', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('specialization', models.TextField(default='', verbose_name='Специализация')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Страховой агент',
                'verbose_name_plural': 'Страховые агенты',
                'ordering': ['-experience_years'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('agent_commission', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Комиссия агента (%)')),
            ],
            options={
                'verbose_name': 'Вид страхования',
                'verbose_name_plural': 'Виды страхования',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('short_content', models.CharField(max_length=200, verbose_name='Краткое содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Скидка (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('valid_until', models.DateField(verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='InsuranceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(editable=False, max_length=14, unique=True)),
                ('insurance_sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Страховая сумма')),
                ('tariff_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Тарифная ставка (%)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuranceagent', verbose_name='Страховой агент')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.client', verbose_name='Клиент')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insurancetype', verbose_name='Вид страхования')),
            ],
            options={
                'verbose_name': 'Договор страхования',
                'verbose_name_plural': 'Договоры страхования',
            },
        ),
    ]
